version: '2.0'
services:
  ansible:
    image: nl2go/ansible:2.7-n2g-1.0.0
    tty: true
    stdin_open: true
    volumes:
      - .:/ansible
      - $HOME$USERPROFILE/.ssh:/tmp/.ssh
    depends_on:
      - crash-test-dummy
  crash-test-dummy:
    build:
      context: .
